### ISSUE TITLE
dceOnPageUid

### ISSUE THREAD

**Issue by withAdaam** [a-r-m-i-n/dce#10]
I have realized a background slideshow with the dce extension. But as there is the same background on each page I handle it over a folder in the page tree which gets implemented into the layout. 

Normaly I would only load the js ans css files if a dce is used on the page using the [dceOnCurrentPage("42")] condition. But as the dce is not on the page but in the folder it does not recognize it. A condition like dceOnPageUid would be prefect to. Do you have a solution for my problem?

**Comment by a-r-m-i-n** [comment]
Hi,
I'm not sure if I understood what you try to achieve. But, when it's about loading assets (JS/CSS) and you are on TYPO3 10 or 11, did you try using the "new" [asset viewhelpers](https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Asset/Index.html)?

When you use them in the DCE templates, you should get what you want.
