### ISSUE TITLE
Editing a only specific fields of a record (e.g. via be.link.editFields with "fields" argument) results in exception

### ISSUE THREAD

**Issue by sypets** [a-r-m-i-n/dce#102]
## Versions
- DCE version: 3.1.2
- TYPO3 version:  12.4 (latest 12.4 branch)
- PHP version: 8.2

## Describe the bug

If the Flexform field of a DCE content element is edited directly (e.g. via be.link.editFields with argument fields), an exception is thrown due to incomplete array in TtContentLabel.php

## Reproduce

1. Create a content element type with DCE
2.  Create a content element of this type
3. Create a BE module and add something like the following (59 is the uid of the CE):

```
<html data-namespace-typo3-fluid="true"
      xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
      xmlns:be="http://typo3.org/ns/TYPO3/CMS/Backend/ViewHelpers"

>
  <be:link.editRecord uid="59" table="tt_content">edit Record 59</be:link.editRecord><br/>
  <be:link.editRecord uid="59" table="tt_content" fields="pi_flexform">edit Record 59 pi_flexform</be:link.editRecord>
</html>

```
4. Click on the second link
5. Click save

An exception is now thrown. With the first link, it does not fail.

## Exception

```
 #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "CType" in /var/www/t3coredev12x/typo3conf/ext/dce/Classes/UserFunction/CustomLabels/TtContentLabel.php line 36
```

## Code

in /var/www/t3coredev12x/typo3conf/ext/dce/Classes/UserFunction/CustomLabels/TtContentLabel.php line 36
```
32    {
33        if (!isset($parameter['row'])) {
34            return;
35        }
36        if ((\is_string($parameter['row']['CType']) || is_array($parameter['row']['CType'])) &&
```

https://github.com/a-r-m-i-n/dce/blob/8459b7fe71e92414ad1aa448f64b01765291c39e/Classes/UserFunction/CustomLabels/TtContentLabel.php#L36

## Impact

In EXT:linkvalidator as well as EXT:brofix, editing only a specific field is being used. I am currently working on support for Flexform fields (which would also include support for dce).

**Comment by begonagarea** [comment]
Could you also apply the fix to the latest compatible version for TYPO3 v11.5, please?
