### ISSUE TITLE
The Update "EXT:container: Migrate "container" sorting" fails always

### ISSUE THREAD

**Issue by bihor** [a-r-m-i-n/dce#105]
**Versions**
- DCE version: **3.1.2**
- TYPO3 version: **12.4.13**
- PHP version: **8.2**

**Describe the bug**
I get in some projects always this error in the Upgrade Wizard:

Thu, 21 Mar 2024 11:47:29 +0100 [CRITICAL] request="467a41b3d8f42" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: BE): TypeError, code #0, file /xxx/vendor/typo3/cms-core/Classes/Http/ApplicationType.php, line 67: TYPO3\CMS\Core\Http\ApplicationType::fromRequest(): Argument #1 ($request) must be of type Psr\Http\Message\ServerRequestInterface, null given, called in /xxx/vendor/t3/dce/Classes/Domain/Repository/DceRepository.php on line 444 - {"mode":"WEB","application_mode":"BE","exception_class":"TypeError","exception_code":0,"file":"/xxx/vendor/typo3/cms-core/Classes/Http/ApplicationType.php","line":67,"message":"TYPO3\\CMS\\Core\\Http\\ApplicationType::fromRequest(): Argument #1 ($request) must be of type Psr\\Http\\Message\\ServerRequestInterface, null given, called in /xxx/vendor/t3/dce/Classes/Domain/Repository/DceRepository.php on line 444","request_url":"https://www.xxx.lu/typo3/install.php?install%5Bcontroller%5D=upgrade&install%5Bcontext%5D=backend","exception":null}

**Comment by a-r-m-i-n** [comment]
Thanks for reporting. Should be easy to fix.

**Comment by Oktopuce** [comment]
I upgrade to DCE version 3.1.3 but the bug is still there.

You forgot one case in file `StandaloneViewFactory.php` line 143:
`
if (ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isFrontend()) {`

instead of:

`if (isset($GLOBALS['TYPO3_REQUEST']) && ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isFrontend()) {`

**Comment by a-r-m-i-n** [comment]
Thanks. I'm going to fix it
