### ISSUE TITLE
Undefined global variable $TYPO3_REQUEST

### ISSUE THREAD

**Issue by bihor** [a-r-m-i-n/dce#106]
**Versions**
- DCE version: **3.1.2**
- TYPO3 version: **12.4.13**
- PHP version: **8.2**

**Describe the bug**
I get sometimes this warning in the Protokoll:

Core: Error handler (BE): PHP Warning: Undefined global variable $TYPO3_REQUEST in /xxx/vendor/t3/dce/Classes/Domain/Repository/DceRepository.php line 444

**Comment by a-r-m-i-n** [comment]
Same issue as in #105
So I'm closing this one, as duplicate.
