### ISSUE TITLE
Rendering problems on other language versions as the main language

### ISSUE THREAD

**Issue by wayheyha** [a-r-m-i-n/dce#11]
**Versions**
- DCE version: **2.8.1**
- TYPO3 version: **10.4.26**
- PHP version: **7.4**

**Describe the bug**
After the upgrade from 2.7.7 to 2.8.1 i noticed something: 
If you have DCE-Elements on a page then every dce element on the page is rendered as the first dce element on the page but only on different languages as the main language. 

After a downgrade from 2.8.1 back to 2.7.7 everything was alright again.

I could reproduce it on two different TYPO3 installations. 

Cheers,
Chris

**Comment by a-r-m-i-n** [comment]
Hi Chris,
I think I already solved this issue, in this commit: https://github.com/a-r-m-i-n/dce/commit/7f6ca87b0c9ec64402b5413ac3cea2972b88abf6

I just did not release it yet. Could you confirm, that the master branch of DCE work?

I'm going to release the new version this weekend, when you confirm, that it works :)

**Comment by a-r-m-i-n** [comment]
This was the related issue: https://github.com/a-r-m-i-n/dce/issues/8

**Comment by a-r-m-i-n** [comment]
Bugfix released last week. Have a nice day.
