### ISSUE TITLE
When using "simple backend view" png and jpg get small SVG get huge

### ISSUE THREAD

**Issue by daUhradone** [a-r-m-i-n/dce#113]
in "simple backend view" jpg and png get rendered or displayed small.
But SVG are not affected and get as big as they are internally set.

Would be nice if they behave like normal images, even if they are added as code and not as file.

<img width="1554" alt="simple-backend-view" src="https://github.com/a-r-m-i-n/dce/assets/75755553/9e5364df-196c-46e6-958a-1b4565e14229">

Thanks

Thomas

**Comment by a-r-m-i-n** [comment]
Hm. To achieve that, I would have to detect that the given code is an svg and add height and width manually. I don't see that in simple backend view feature of DCE. Regulary added svg images should get resized. 

Instead I would recommend to use the manual backend template feature: https://docs.typo3.org/p/t3/dce/main/en-us/UsersManual/BackendTemplate.html#manual-backend-fluid-template

And provide the markup and styles required, to resize the svg contents.
