### ISSUE TITLE
DCE field definitions workspace enabled

### ISSUE THREAD

**Issue by nhovratov** [a-r-m-i-n/dce#115]
**Versions**
- DCE version: **2.9.5**

Hi! Just had an odd issue in an old installation with DCE and wanted to leave a comment. Apparently it is possible to versionate DCE field definitions in workspaces. I don't know if this is intended, however this leads to FlexForm field definitions being generated twice (live + workspace version). I suppose somewhere is a workspaces restriction missing.

In my opinion DCE definitions shouldn't be workspace aware. But if this is intented, then the missing workspace restriction should be added at least.

Greetings, Nikita

**Comment by a-r-m-i-n** [comment]
Hi Nikita,
I agree with you. DCEs and DCE fields shouldn't support workspaces. In TCA configuration of both tables workspaces are not enabled. So I'm curious that you have issues with that.

Versioning on the other hand is enabled, but this is not a workspace related feature (AFAIK).

Could you please describe what steps you did, to reproduce this issue? Thanks.

**Comment by nhovratov** [comment]
Hi Armin, thanks for the reply.
I see, so maybe workspaces was enabled at some time before? I don't really know how these workspace overlay records were created back then. I only know that these were causing trouble. So I guess it's not possible to reproduce, except maybe if you enable workspaces again and edit a dce field in another workspace.

I think this can be closed then, as this issue won't occur on current versions. For troubleshooting purposes it is nice to have this issue here at least.
