### ISSUE TITLE
does type "flex" is possible in field configuration?

### ISSUE THREAD

**Issue by Pistil-Studio** [a-r-m-i-n/dce#116]
I whant to use an external DS configuration for my field, impossible to setting up :( (DCE 2.0.6 used due to old v9 instance)

I try something like this ? 

```xml
<config>
	<type>flex</type>
	<ds>
		<default>
FILE:EXT:ps_tracking/Configuration/FlexForms/OverridesPages.xml
		</default>
	</ds>
</config>

```

I have alway the error : Data Structure ERROR: No ['ROOT']['el'] element found in flex form definition
I tested many variations

Thx a lot

**Comment by a-r-m-i-n** [comment]
Hi!
Actually, I've never tried that. I'm also not sure, if TYPO3 does support the usage of type: flex inside of a flexform (which would mean: nesting flexform).

Also, there is currently no other possibility implemented to DCE to outsource the field configuration to external files.
