### ISSUE TITLE
PHP Error Undefined array key "header"

### ISSUE THREAD

**Issue by gmt-it** [a-r-m-i-n/dce#121]
**Versions**
- DCE version: **3.2.0**
- TYPO3 version: **13.2.1**
- PHP version: **8.22**

**Describe the bug**
After installing DCE, I can no longer change content elements. Every time I try, I get the following error:

TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "header" in /var/www/html/vendor/t3/dce/Classes/UserFunction/CustomLabels/TtContentLabel.php line 76

[typo3_11f96f4e3a.log](https://github.com/user-attachments/files/16763508/typo3_11f96f4e3a.log)

**Comment by a-r-m-i-n** [comment]
Thanks for reporting. I'm trying to reproduce the issue and fix it as soon as possible

**Comment by a-r-m-i-n** [comment]
Okay. It took a while to reproduce this issue. But when I change the CType of a content element, then this issue occures.

**Comment by a-r-m-i-n** [comment]
It is fixed in release 3.2.1 of the DCE extension
