### ISSUE TITLE
Not usable with TYPO3 Version 13.3.0

### ISSUE THREAD

**Issue by misterbond007** [a-r-m-i-n/dce#127]
Versions

    DCE version: 3.2.1
    TYPO3 version: 13.3.0
    PHP version: 8.3.11

Describe the bug
Installation under TYPO3 Version 13.3.0 does work, nevertheless after opening the module DCE the error is "(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException

Tried resolving a template file for controller action "Default->Default" in format ".html", but none of the paths contained the expected template file (Default/Default.html). The following paths were checked: C:/inetpub/XXX/typo3/sysext/backend/Resources/Private/Templates/, C:/inetpub/XXX/typo3conf/ext/dce/Resources/Private/Templates/".

No problems with TYPO3 Version 13.2.1.

**Comment by a-r-m-i-n** [comment]
Hm. I get a different error message:

> TYPO3\CMS\Extbase\Persistence\Generic\Mapper\DataMapper::thawObjectProperty(): Return value must be of type ?object, array returned in /var/www/html/vendor/typo3/cms-extbase/Classes/Persistence/Generic/Mapper/DataMapper.php line 308

This error appears when trying to open the DCE module or when opening a page, containing DCE items, in list or page module.

**Comment by a-r-m-i-n** [comment]
I've opened an issue in TYPO3's forge: https://forge.typo3.org/issues/105062

This DataMapper exception, seems to be core related.

**Comment by a-r-m-i-n** [comment]
Okay, after fixing this DataMapper exception, I get the same issue, you got, regarding the DceModule in backend.

**Comment by nhovratov** [comment]
You need to set the template name explicitly like this

```
        return $this->moduleTemplate->renderResponse('DceModule/Index');
```
Can't say why it worked before, but the Core defines it everywhere.

**Comment by misterbond007** [comment]
Where do I have to set this? When I install the extension and open the module dce, I don‘t have a fluid dce template at this time.

**Comment by nhovratov** [comment]
dce has to set this, not you as the user :)

**Comment by a-r-m-i-n** [comment]
I'm going to fix this, soon. There are several issues in v13 left, needing my attention.
