### ISSUE TITLE
2.8.2 breaks t3:// templates

### ISSUE THREAD

**Issue by Ceremony64** [a-r-m-i-n/dce#14]
**Versions**
- DCE version: **2.8.2**
- TYPO3 version: **10.4.26**
- PHP version: **7.4**

With 2.8.2 "t3://" paths for templates  such as "t3://file?uid=1234" stopped working. I suspect file: paths have the same issue, but I have not tested it yet.

I don't think this is intended behavior, as the changelog states that this file reference feature is now only marked as deprecated. It is not yet a breaking change, where support for it is actually dropped.

**Comment by neonic** [comment]
Same Versions here and the following error shows up:
PHP Warning: file_get_contents(/serverpath/httpdocsfileadmin/_templates/dce/dce-template.html)
The slash before fileadmin is missing.

**Comment by a-r-m-i-n** [comment]
@Ceremony64 Thanks for Reporting!
@neonic  Thanks for the hint, with missing slash.

I've provided a patch, could you check if this fixes the issue for you?

---

But keep in mind, that using t3:// is being marked as deprecated and will not work anymore in DCE 3.0.

**Comment by neonic** [comment]
Yes, it is fixed.

**Comment by a-r-m-i-n** [comment]
Okay. But strage, because on my local machine, it worked without this extra slash. However. Extra slashes do not hurt. Missing slashes do. Thanks!

**Comment by a-r-m-i-n** [comment]
New version 2.8.3 containing this fix, is being released.

**Comment by neonic** [comment]
Thank you.
