### ISSUE TITLE
Order of a section may get shuffled when deleting an section entry

### ISSUE THREAD

**Issue by Ceremony64** [a-r-m-i-n/dce#20]
There is some weird behavior when deleting an element from a longer section, as in it sometimes reorders the section elements somewhat randomly, tho there does seem to be some kind of pattern to it.

My simple DCE element:
![image](https://user-images.githubusercontent.com/5873369/166883137-87aad292-e1a8-4f5e-965d-a872597ccbf6.png)
![image](https://user-images.githubusercontent.com/5873369/166883645-49ebe21f-a71a-4aa4-bbff-27dc68731be2.png)

Now I create the content element based on the DCE element and add 20 section entries numbered 1 to 20 (left backend, right frontend):
![image](https://user-images.githubusercontent.com/5873369/166882911-14fefbb3-c9fb-4199-bc90-375cde65fe56.png)![image](https://user-images.githubusercontent.com/5873369/166883881-3b1e291e-e82e-4687-8a86-0c681c65c34d.png)

So far, so good. However, when I now delete the 5th entry (or basically any other) and save, the the order gets shuffled (left backend, right frontend):
![image](https://user-images.githubusercontent.com/5873369/166883481-1a1c4f8f-72d6-4c0b-909c-442f50dd49ee.png)![image](https://user-images.githubusercontent.com/5873369/166883688-05c895fb-c82f-4dc9-96c7-5817195a2ac6.png)

Also, this does not always occur and I couldn't reliable replicate the issue with fewer section entries like 10 or so, but it happened every time when starting with 20 section entries tho.

I am running DCE v2.8.4 and Typo3 v10.4.27

**Comment by a-r-m-i-n** [comment]
I am sorry, but the behaviour of sections itself is TYPO3 core related. DCE just provides an interface to build the required flexform configuration, to get those sections.

And btw. I strongly recommend to avoid the usage of sections.
