### ISSUE TITLE
Problem with config field type: file upload

### ISSUE THREAD

**Issue by cwplus** [a-r-m-i-n/dce#21]
**Versions**
- DCE version: **2.8.4**
- TYPO3 version: **10.4.28**
- PHP version: **7.4**

**Describe the bug**
when i add field type : upload file in my custom dce, and i add content type my custom dce, i have error like

TCA internal_type of field "settings.myfield" in table tt_content must be set to "db" or "folder".

![Screenshot_29](https://user-images.githubusercontent.com/5727109/169988640-6a7c6791-9450-4805-955d-df722b0eed86.png)
![Screenshot_30](https://user-images.githubusercontent.com/5727109/169988639-40e192d1-5134-4c7d-86ab-45adfdc7f404.png)
![Screenshot_31](https://user-images.githubusercontent.com/5727109/169988630-f6b7d0b1-bb11-443b-a7e1-9f24b89b2807.png)

I checked also with : 
- DCE version: **2.6.2**
- TYPO3 version: **10.4.21**
- PHP version: **7.2**
and ï've had the same error

**Comment by a-r-m-i-n** [comment]
Sorry, but `internal_type => file` is not supported anymore: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5/Deprecation-86406-TCATypeGroupInternal_typeFileAndFile_reference.html

In case you have old instances with this configuration running, you can migrate them with the brand new File2Fal Upgrade wizard, which will be released in DCE 2.9.0 (see docs: https://docs.typo3.org/p/t3/dce/main/en-us/AdministratorManual/UpgradeWizards.html#filetofalupdate)
