### ISSUE TITLE
Undefined array key "_LOCALIZED_UID" in FalViewHelper

### ISSUE THREAD

**Issue by sbuerk** [a-r-m-i-n/dce#22]
**Versions**
- DCE version: **2.8.4**
- TYPO3 version: **11.5.10**
- PHP version: **8.1**

**Describe the bug**

PHP Warning: Undefined array key "_LOCALIZED_UID" in <project-path>/public/typo3conf/ext/dce/Classes/ViewHelpers/FalViewHelper.php line 64

Looked into the code, still not fixed there. I think there should be multiple array key access guards added there anyway.

![image](https://user-images.githubusercontent.com/1453466/170241962-c703d4e9-ef3d-4494-bdbd-020e35fb5e05.png)

**Comment by a-r-m-i-n** [comment]
Fixed in c4d4746c3f5275ffd0738e4d77a67f8fcf8ac68c
