### ISSUE TITLE
Upgrade Wizard Bug (DCE 2.9.1 - Typo3 11.15.16)

### ISSUE THREAD

**Issue by uzerterter** [a-r-m-i-n/dce#29]
Hi, I wanted to inform you that a problem with the Upgrade Wizard persists in version 2.9.1 (with Typo3 Version 11.15.16).
(I thought that maybe it is better to open a new issue for this)

When clicking on "Run Upgrade Wizard" in the Install Tool (or BE) while DCE is installed the same 503 Error message appears as mentioned  in https://github.com/a-r-m-i-n/dce/issues/28#issue-1324362856.

When activating ['SYS']['exceptionalErrors'] => 12290, additional information is displayed:

![DceErrorScreenshot](https://user-images.githubusercontent.com/65909766/190220577-d5fd10a5-901f-456c-a192-59835222e4a7.png)

_Originally posted by @uzerterter in https://github.com/a-r-m-i-n/dce/issues/28#issuecomment-1247077103_

**Comment by a-r-m-i-n** [comment]
Hi, thanks for reporting! 
It seems that you still have content elements existing (which are not deleted), which point to a deleted DCE.

Please undelete this DCE  (set "deleted" to 0) or delete those content elements.

Nevertheless, instead of throwing an exception, this record should just get skipped and maybe logged.

**Comment by uzerterter** [comment]
Hi, sorry for taking so long to answer.
To my knowledge I do not have any deleted DCE in this installation, I could not find any marked as deleted in the DB.

**Comment by a-r-m-i-n** [comment]
Okay. I was able to reconstruct the issue. When a DCE is inactive this error occures. I'm going to fix it... :)

**Comment by a-r-m-i-n** [comment]
The issue is fixed in version 2.9.2

**Comment by wowaTYPO3** [comment]
Hi Armin, unfortunately this error still occurs with version 2.9.2 and TYPO3 10.4.32. Since I have time pressure with this upgrade: is there a quick workaround?
