### ISSUE TITLE
Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\Link\TypolinkViewHelper: useCacheHash

### ISSUE THREAD

**Issue by dennisrembecki** [a-r-m-i-n/dce#31]
We updated from DCE 1.6 some time ago and everything worked on Typo3 10.

After updating to Typo3 11.5.16, DCE 2.9.1 throws this error:

```
Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\Link\TypolinkViewHelper: useCacheHash. Valid arguments are: parameter, target, class, title, language, additionalParams, additionalAttributes, addQueryString, addQueryStringMethod, addQueryStringExclude, absolute, parts-as, textWrap
```

Last entry in DCE before going to Typo3 Core:
```
at TYPO3Fluid\Fluid\View\AbstractTemplateView->render()
in /var/www/zoechling-holz.rv-works.dev/httpdocs/typo3conf/ext/dce/Classes/Domain/Model/Dce.php line 868
```

I recreated typoconf/autoload, flushed Cache, did the Update Wizard and Database Compare.

**Comment by a-r-m-i-n** [comment]
Hi @dennisrembecki,
this exception happens because of an error in your fluid template. I assume you've upgraded to a newer TYPO3 version, and there the argument "useCacheHash" of typolink viewhelper is not existing anymore.

This is nothing I could fix in DCE for you.

**Comment by dennisrembecki** [comment]
Okay thank you anyway, i deleted all "useCacheHash" entries from one of the DCE Databases and the Error is gone.
