### ISSUE TITLE
File-upload for fluid-template (DCE Record) is missing

### ISSUE THREAD

**Issue by lexi80** [a-r-m-i-n/dce#32]
**Versions**
- DCE version: **2.9.1**
- TYPO3 version: **11.5.15**
- PHP version: **7.4** 

**Describe the bug**
File-upload for fluid-template (DCE record) is missing. Therefore (probably) DCE-element will not be rendered in frontend.

**Comment by lexi80** [comment]
just found this [[issue]()](https://github.com/a-r-m-i-n/dce/issues/3) (closed)... seems to be the same problem. when i link the fluid-template with the path of the file "fileadmin/..." it works.

**Comment by a-r-m-i-n** [comment]
Hi, I assume that your issue is solved, with using "fileadmin/..." paths.
