### ISSUE TITLE
Argument 1 passed to T3\Dce\Domain\Repository\DceRepository::findByUidIncludingHidden() must be of the type int, null given

### ISSUE THREAD

**Issue by fixpunkt-systeme** [a-r-m-i-n/dce#35]
**Versions**
- DCE version: **2.9.2**
- TYPO3 version: **10.4.32**
- PHP version: **7.4.11**

**Describe the bug**
When I click at "System -> Reports" or the "Upgrate Wizard" I get this error:
 TypeError

Argument 1 passed to T3\Dce\Domain\Repository\DceRepository::findByUidIncludingHidden() must be of the type int, null given, called in C:\xampp\htdocs\git\typo3-bildkunst\public\typo3conf\ext\dce\Classes\UpdateWizards\FileToFalUpdateWizard.php on line 103

Solution: add this if-statement:
 if (isset($affectedDceRow['uid'])) { ... }

**Comment by a-r-m-i-n** [comment]
Thanks for reporting. I think I already fixed this issue, in latest master. It's just not released, yet.
