### ISSUE TITLE
Using standard image field for mapping causes error

### ISSUE THREAD

**Issue by TBschen** [a-r-m-i-n/dce#39]
**Versions**
- DCE version: **2.9.3**
- TYPO3 version: **11.5.17**
- PHP version: **7.4**

**Describe the bug**
I create a fresh TYPO3 11 installation with DCE, then I did:
- create a new DCE
- create an FAL field using the suggested configuration (https://github.com/a-r-m-i-n/dce/files/9921386/configuration.txt)
 and fill out other required fields
- Map field value to TCA column -> existing field "image - Integer"
- save the DCE
- create a page and use the DCE you just created
- insert an image and save
- I get the error:

> 503
> Oops, an error occurred!
> An exception occurred while executing 'UPDATE tt_content SET image = ? WHERE uid = ?' with params ["NEW636280595631b052851626", 4]: Incorrect integer value: 'NEW636280595631b052851626' for column database.tt_content.image at row 1

Now I can fix it for already created elements by clicking on "Update TCA mappings", but doing so for every new element isn't a good workflow :)

**Comment by a-r-m-i-n** [comment]
You can not map a FAL field to any column. You should only get the amount of sys_file_references, instead of uids.

However, to fix your issue just use a non-integer column or let DCE create a new one.

**Comment by TBschen** [comment]
That's interesting. So this is something that has been changed in TYPO3 11 since it used to work in TYPO3 10.
