### ISSUE TITLE
Dependency repositories ext-json/ext-dom not available anymore

### ISSUE THREAD

**Issue by imptingdesign** [a-r-m-i-n/dce#48]
Hey

just wanted to update from DCE v2.6.2 to 2.9.3 via Composer (Composer-based project) but unfortunately the repositories for ext-json and ext-dom are gone (or now private). 
I'm running <code>ddev composer req t3/dce</code> and the output is:

<code>Info from https://repo.packagist.org: #StandWithUkraine                                                  
./composer.json has been updated                                                                         
Running composer update t3/dce                                                                           
Loading composer repositories with package information
Updating dependencies                                 
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 4 updates, 0 removals
Downloading ext-json/ext-json (dev-main b4052aa)
 0/1 [>---------------------------]   0%    Failed to download ext-json/ext-json from dist: The "https://api.github.com/repos/alirezac0/SomeBBShit/zipball/b4052aa796309eb390f4c61cec10124d71b5ad90" file could not be downloaded (HTTP/2 404 ):
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#download-a-repository-archive"}</code>

Any ideas how to continue? As long as the repos don't come back, you can't update.....

Thanks 
Matthias

**Comment by a-r-m-i-n** [comment]
Check your error output. The package ext-json/ext-json is causing your issue...

**Comment by imptingdesign** [comment]
Thanks Armin, but how is that supposed to help me? 
Yes, the package is causing the issue because the github repo is no longer available, at least I can't find it when searching via name or the repo author..
