### ISSUE TITLE
Wrong File Path in Composer mode

### ISSUE THREAD

**Issue by ohm-meter** [a-r-m-i-n/dce#53]
**Versions**
- DCE version: **2.9.3**
- TYPO3 version: **11.5.26**
- PHP version: **8.1**
- Typo3 Composer Mode 
- 
**Describe the bug**
If i use the new   Composer mode. To be fit for TYPO3 V12.

See https://github.com/TYPO3/CmsComposerInstallers/releases/tag/v4.0.0-RC1  and https://b13.com/core-insights/typo3-and-composer-weve-come-a-long-way then  the Codemirror Code in the Backend is not loaded. Console says wrong MIME Type because the Url for CSS Point to HTML instead to CSS.

I have made a new Commit for that
https://github.com/a-r-m-i-n/dce/compare/master...i-kiu:dce:master

**Comment by a-r-m-i-n** [comment]
Composer Installer Script v4-RC1 is not supported yet and never will be.

New updated DCE version for TYPO3 12 will face this issue. In TYPO3 11 please use the regular way of asset handling or use [helhum/secure-web](https://packagist.org/packages/helhum/typo3-secure-web).

So, this seems to be a duplicate to #54 for me.
