### ISSUE TITLE
the provided typolink code still has "useCacheHash"

### ISSUE THREAD

**Issue by daUhradone** [a-r-m-i-n/dce#56]
**Versions**
- DCE version: **2.9.4**
- TYPO3 version: **11**
- PHP version: **7.x**

**Describe the bug**
To create a link field the provided code still has "useCashHash" at the end of the link this generates an error.

**Comment by a-r-m-i-n** [comment]
Please show the fluid you've used to create the link.

**Comment by daUhradone** [comment]
under template -> dropdown menu -> Template content (fluid) -> famous viewhelper -> f:link.typolink 
creates this:

```
<f:link.typolink parameter="{field.link}" target="_blank" class="ico-class" title="some title" useCacheHash="true">
    Linktext
</f:link.typolink>
```

useCacheHash then creates an overall typo3 error

**Comment by a-r-m-i-n** [comment]
Yes. Confirmed.
