### ISSUE TITLE
copy and paste of DCEs with the TYPO3 system

### ISSUE THREAD

**Issue by daUhradone** [a-r-m-i-n/dce#59]
**Versions**
- DCE version: **2.x.x**
- TYPO3 version: **11**
- PHP version: **7.x**

**Describe the bug**
Sometimes a DCE is a good starting point for a new one, if they are quite similar. But using the TYPO3 copy and paste system in list view doesn't work as expected. Usually you loose most of the input fields or you even get input fields from other DCEs.

**Comment by a-r-m-i-n** [comment]
I tested copy and pasting a DCE in latest version (3.0) in TYPO3 12, and it works as expected.

**Comment by daUhradone** [comment]
So, let's look forward to T12
THX for checking!


Enclosed a PDF with screenshots with the bug still active for TYPO3 11.5.16 and DCE 2.9.1 tested 15. Aug 2023

[DCEs-copy-Bug-T11.pdf](https://github.com/a-r-m-i-n/dce/files/12343728/DCEs-copy-Bug-T11.pdf)
