### ISSUE TITLE
[bug] When editinga DCE directly from the file manager. Links are not updating.

### ISSUE THREAD

**Issue by Scopestyle** [a-r-m-i-n/dce#60]
**Versions**
- DCE version: **2.9.3**
- TYPO3 version: **11.5.24 / 11.5.25**
- PHP version: **7.4 / 8.2**

**Describe the bug**

In short: When editing a DCE directly from the File Manager / Dateiliste. Links are not updating.

In our case, we have a simple Download list module (Repeating DCE List with a Name & Link Flexform). A client wants to update his old download files for new ones. So he went into the file manager, and looked at which DCE modules reference the old download files. He then opens one of the DCE Download Modules referencing the file. Which opens neatly in a frame. He starts changing the links, but after selecting a new file the link input never updates, and the old file never updates. This is an issue only with the Typolink configuration.

I found out that when opening the module directly on for example the downloads page. The links are being updated just fine. So this is a problem with the view from File Manager. I tested this scenario in another project, and could confirm the same behaviour.

![01](https://github.com/a-r-m-i-n/dce/assets/6349562/f2ff58a0-4a8e-4b04-a9c9-44623fffb9f0)
_1: Open file from file manager_

![02](https://github.com/a-r-m-i-n/dce/assets/6349562/c3ac36fc-5056-4c52-8d29-e4f2a7c7e893)
_2: See which modules reference the file_

![03](https://github.com/a-r-m-i-n/dce/assets/6349562/c5471caf-5267-410f-bd39-bb01a9910bf2)
_3: Edit the file directly in the module overlay (this is not working)_

**Comment by a-r-m-i-n** [comment]
I am sorry, but this sounds heavily like a core issue. Also, your DCE contain sections. I bet there is a Javascript issue existing, which has problems to put the value selected in link wizard, to the input field within the section, within this fancy file list overlay.

When you enter the link value manually right in the input field, it works. Right?

**Comment by Scopestyle** [comment]
Hi Armin, You are correct, manually replacing IDs seems to work.

**Comment by a-r-m-i-n** [comment]
Okay. Then please create an issue on forge.typo3.org Thank you :)

**Comment by Scopestyle** [comment]
Done! https://forge.typo3.org/issues/100980
