### ISSUE TITLE
<f:debug>{_all}</f:debug> does not work in template fluid area

### ISSUE THREAD

**Issue by ms-wa** [a-r-m-i-n/dce#64]
**Versions**
- DCE version: **2.9.4**
- TYPO3 version: **11.5.28**
- PHP version: **8.1**

**Describe the bug**
Debugging all variables does not work, when you want to debug some variables it works.
![Bildschirmfoto 2023-07-14 um 11 45 15](https://github.com/a-r-m-i-n/dce/assets/100279082/6320e97e-c3f1-4b6a-8013-aec2d3bdd4ec)

i have a new information, you have the debug problem only when the typo3 system is in the debug mode.

**Comment by a-r-m-i-n** [comment]
Interesting...

**Comment by ms-wa** [comment]
i have a new information, you have the debug problem only when the typo3 system is in the debug mode.

**Comment by a-r-m-i-n** [comment]
Sorry, but I'm unable to reconstruct this issue:
![image](https://github.com/a-r-m-i-n/dce/assets/1275298/651a3e0c-4be1-4f6a-aaf4-f244891408d5)

**Comment by a-r-m-i-n** [comment]
Ahh, my fault. I am able to reconstruct 😅

**Comment by a-r-m-i-n** [comment]
Okay, the issue also occures, when you try to debug `{dce}`. 
It seems that the DebuggerUtility of TYPO3 core has issues, with static properties on PHP 8+ for persisted entities.

I've created an issue on forge for that: https://forge.typo3.org/issues/101488

**Comment by a-r-m-i-n** [comment]
Until this is fixed, you need to disable PHP warnings in TYPO3 settings, to restore debug output
