### ISSUE TITLE
DCE: Frontend-fluid-paths not working?!

### ISSUE THREAD

**Issue by subnoodle** [a-r-m-i-n/dce#65]
**Versions**
- DCE version: **2.9.4**
- TYPO3 version: **11.5.27**
- PHP version: **8.1.13**

**Describe the bug**
Hi Armin, 

i discoverd a bug, as far as i can see:

You described the TS-setup here: 
https://docs.typo3.org/p/t3/dce/main/en-us/AdministratorManual/TyposcriptConfiguration.html#

I use this one in the code:

```
# DCE - config - include fluid-styled-content-partials for DCE
plugin.tx_dce.view {
  templateRootPaths {
    10 = EXT:vb_frontend/Resources/Private/ext/dce/
    20 = EXT:fluid_styled_content/Resources/ext/fluid_styled_content/Private/Templates/
    30 = EXT:fluid_styled_content/Resources/Private/Templates/
  }

  partialRootPaths {
    10 = EXT:vb_frontend/Resources/Private/ext/dce/Partials/
    20 = EXT:vb_frontend/Resources/Private/ext/fluid_styled_content/Partials/
    30 = EXT:fluid_styled_content/Resources/Private/Partials/
  }

  layoutRootPaths {
    10 = EXT:vb_frontend/Resources/Private/ext/dce/Layouts/
    20 = EXT:fluid_styled_content/Resources/Private/Layouts/
  }
}
```

There is no way to get layouts works, except when providing it in den DCE-Module >> DCE-Element >> Misc-Tab >> Layout-Path.
But this is not what we need here.

We would need a working Fuild-Path-Setup.

The behavior instead is like:

- Regardless, if plugin.tx_dce.view is here or not, it's never considered for renderung DCE-Frontends;
- I can delete the snippets above by deleting all the lines: the paths in plugin.tx_dce.view are not defined by DCE itself; does not change anything;
- I can delete it by `plugin.tx_dce.view >`  - does not affekt anything;
- I can change the order of the single lines with the paths: does not affect anything

So, it seems the path setup by plugin.tx_dce.view is not considered at all in the frontend.
So, the basic question is, IF it is intended to work with these pahts, as the documentation tells?

Thank you for your feedback!

Thomas

**Comment by a-r-m-i-n** [comment]
I am sorry, but I can't reconstruct this issue. When I use your typoscript config and set layout to "Default", I get this output:
```
<div id="c" class="frame frame- frame-type- frame-layout-">
















    <div class="dce">
        Your template goes here...
    </div>













</div>
```

Basically, resolving the layout file works. DCE is passing the current tt_content row to fluid using the variable "contentObject", but the Default layout of fsc expects "data". In order to make it more compatible, I've added the variable as alias, so the Default layout will return this now:

```
<div id="c1" class="frame frame-default frame-type-dce_issue-65 frame-layout-0">
```
