### ISSUE TITLE
Possibility of a DisplayCond for section

### ISSUE THREAD

**Issue by derMatze82** [a-r-m-i-n/dce#67]
Is there a way to hide an entire section? If I assign a DisplayCondition to the individual fields of the section, they are not displayed, but an empty element can be created and then leads to an error when saved.

**Comment by a-r-m-i-n** [comment]
No, this is not possible. Also, you should avoid to use section fields.

**Comment by derMatze82** [comment]
What would you recommend instead if you want to create multi-elements?

**Comment by a-r-m-i-n** [comment]
EXT:container if you need physical containers (which actually exists in database) or the built in DCE Container, if logical containers (without own properties) works for you.
