### ISSUE TITLE
Missing public Service FileToFalUpdateWizard in Services.yaml

### ISSUE THREAD

**Issue by derMatze82** [a-r-m-i-n/dce#68]
**Versions**
- DCE version: **dev-compatibility-12**
- TYPO3 version: **12.4**
- PHP version: **8.2**

if you use e.g. the Upgrade Wizard, an exception occurs: `Uncaught TYPO3 Exception Too few arguments to function T3\Dce\UpdateWizards\FileToFalUpdateWizard::__construct(), 0 passed in /usr/share/nginx/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php on line 2969 and exactly 2 expected thrown in file /usr/share/nginx/html/vendor/t3/dce/Classes/UpdateWizards/FileToFalUpdateWizard.php
thrown in file /usr/share/nginx/html/vendor/t3/dce/Classes/UpdateWizards/FileToFalUpdateWizard.php
in line 52`

This could be fixed adding
```
    T3\Dce\UpdateWizards\FileToFalUpdateWizard:
        public: true
```
to Services.yaml

**Comment by a-r-m-i-n** [comment]
Already fixed. Thanks.
