### ISSUE TITLE
Uncaught TYPO3 Exception in Classes/Components/ContentElementGenerator/OutputPlugin.php

### ISSUE THREAD

**Issue by maslme** [a-r-m-i-n/dce#7]
When running typo3/sysext/core/bin/typo3 scheduler:run from a cronjob I got the following error:

Uncaught TYPO3 Exception syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING)
thrown in file [...]/typo3conf/ext/dce/Classes/Components/ContentElementGenerator/OutputPlugin.php
in line 54

I also got this error when testing the code with an online php parser.

Systeminformation:
TYPO3 10.4.24 classic installation (non-composer)
PHP 7.2.23
dce 2.8.1 and latest github version

**Comment by a-r-m-i-n** [comment]
Hi. You are running a not supported PHP version. DCE requires at least PHP 7.3.
I know that TYPO3 10 still runs on PHP 7.2, but because maintenance for PHP 7.2 ended, I do not support it anymore.

And you shouldn't use this old, **unsupported** PHP version anymore, too! ;-)

**Comment by maslme** [comment]
Thanks for your hint @a-r-m-i-n
