### ISSUE TITLE
Images disappeared after update to Typo3 12

### ISSUE THREAD

**Issue by schnappenberger** [a-r-m-i-n/dce#71]
**Versions**
- DCE version: **3.0.0**
- TYPO3 version: **12.4.5**
- PHP version: **8.2.8**

**Describe the bug**
If we update an existing website with images from Typo3 11 to Typo 3 12 none of the images are displayed (backend and frontend). The result stays the same before and after executing all upgrade wizards and database updates.

If we change the field "fieldname" in table "sys_file_referance" from {variablename} to settings.{variablename} (f.e. img to settings.img) the images are visible in frontend and backend again

**Comment by a-r-m-i-n** [comment]
Hi! Thanks for reporting. 

You should use the new type: file TCA type, instead of inline. Then, images should get displayed properly again.

The new upgrade wizard https://github.com/a-r-m-i-n/dce/blob/master/Classes/UpdateWizards/InlineFalToFileUpdateWizard.php should do this for you.

**Comment by schnappenberger** [comment]
The upgrade wizard was executed already and the configuration of the dce fields were updated succesful to the new TCA type. But the existing images stay invisible in backend and frontend.

I have added a new image element. In that case the fieldname in sys_file_reference was set to settings.img. But existing file_references were not updated and keep their fieldname "img".

I cant see any place in the code InlineFalToFileUpdateWizard where existing filereference fieldnames are updated. Am i missing something?

PS: Thanks for your great work!

**Comment by a-r-m-i-n** [comment]
Oh, you are right. I tested the migration from inline to file type, but the initial images I've added to test, we're added in v12. So, there the new fieldname (prepended with "settings.") were already correct.

This requires another upgrade wizard, which is not written yet, to update the records in sys_file_reference.

I'm trying to achieve this the upcoming weekend.
