### ISSUE TITLE
Required Fields not marked in Flexform any more

### ISSUE THREAD

**Issue by vincentvega123** [a-r-m-i-n/dce#75]
The defined required fields from the configuration are forced to be filled in the flexform in general, but the fields are not marked explicitly any more.

![Bildschirmfoto 2023-08-28 um 13 02 55](https://github.com/a-r-m-i-n/dce/assets/10086856/f8cd29a2-5f10-4ef3-8696-27d279c954f5)

```
<config>
	<type>input</type>
	<size>30</size>
	<eval>trim,required</eval>
</config>
```

Typo3 12.4.5
DCE 3.0.1

**Comment by a-r-m-i-n** [comment]
This is a core issue. Please open an issue on forge.typo3.org.

And btw. to mark a field as required you have to use `<required>1</required>` in v12.
The eval syntax causes deprecation notices, and will not work in v13 anymore.
