### ISSUE TITLE
Container multi language (free mode) issue in 2.8.1

### ISSUE THREAD

**Issue by e3debie** [a-r-m-i-n/dce#8]
**Scenario:**
-Simple DCE with wrapping container ("Enable DCE container" = true and "Enable detail page" -> false)
-everything works fine on default language -> sys_language_id = 0
-on sys_language_id = 1, the dce container has the right number of elements inside, but they are all the same (equal to the first element) 
-Version 2.8.0 does not have this issue -> I found lines 182 - 186 in Classes\Components\DceContainer\ContainerFactory.php to be guilty of this behaviour. Those lines are not present in 2.8.0, i guess those lines fix another issue but cause this new one.

**Note:**
I only tested this with "Free mode" -> not with the other modes.
Also tested only TYPO3 versions 10.4.23 and 10.4.25

Best regards
Sascha

**Comment by a-r-m-i-n** [comment]
Hi Sascha, thanks for reporting! 
Indeed I think it is this commit which causes the issue: https://github.com/a-r-m-i-n/dce/commit/fb206702bbb6fb06325130cb69e14bf1759afe5a

I think this condition is the problem: ``$rawContentElement['uid'] !== $rawContentElement['l18n_parent']`` 

It is also true, when ``$rawContentElement['l18n_parent']`` is `null`. So could you test if an ``!empty($rawContentElement['l18n_parent'])`` in this condition would work for you?

**Comment by e3debie** [comment]
Hi Armin,

checked that right away.

**replaced:**
`if ($rawContentElement['sys_language_uid'] > 0 && $rawContentElement['uid'] !== $rawContentElement['l18n_parent'] && !isset($rawContentElement['_LOCALIZED_UID'])) {`

**with:**
`if ($rawContentElement['sys_language_uid'] > 0 && !empty($rawContentElement['l18n_parent']) && $rawContentElement['uid'] !== $rawContentElement['l18n_parent'] && !isset($rawContentElement['_LOCALIZED_UID'])) {`

Result -> works fine and solves this issue for my specific case :-)

Best regards
Sascha
