### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ste101** [a-r-m-i-n/dce#85]
**Versions**
- DCE version: **3.1.0**
- TYPO3 version: **12.4**
- PHP version: **8.2**
- non-compser

**Describe the bug**
In backend or frontend when showing a DCE-Element:
`T3\Dce\Utility\TypoScript::__construct(): Argument #1 ($typoScriptService) must be of type TYPO3\CMS\Core\TypoScript\TypoScriptService, TYPO3\CMS\Extbase\Configuration\ConfigurationManager given, called in /htdocs/typo3-12/typo3_src-12.4.6/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3000`

**Comment by a-r-m-i-n** [comment]
Sounds like you did not clear all caches in the install tool after updating. Please do this and report, if your issue still occurs.
