### ISSUE TITLE
Unable to resolve specifier '@t3/dce/code-editor' with template type "File"

### ISSUE THREAD

**Issue by schnappenberger** [a-r-m-i-n/dce#86]
**Versions**
- DCE version: **3.1.0**
- TYPO3 version: **12.4.6**
- PHP version: **8.2**

**Describe the bug**
The confiugration textarea of the dce doesn’t adapt its height and doesn’t react to changes in the select box if a dce has template type "File". The javascript module @t3/dce/code-editor cannot be loaded in this case. I think it’s because the template_content field is hidden in this case (this field has the render type dceCodeMirrorField which adds the javascript module).

Steps to reproduce:
1. Create a new dce and add a field
2. Change the template type to file
3. Save and close the dce
4. Reopen the dce
5. Open a field
6. Have a look at the textarea (3 rows high)
7. Try to change the configuration by selecting an entry from the select box (Nothing happens)

**Comment by a-r-m-i-n** [comment]
Thanks for reporting. I was able to reconstruct the issue and fixed it. The fix is released in version 3.1.1 of DCE extension :)

**Comment by a-r-m-i-n** [comment]
I've also opened an issue on Forge, because I think it is an core issue, that the JavaScriptModules do not get loaded, when located in an IRRE element: https://forge.typo3.org/issues/102111
