### ISSUE TITLE
DatabaseUtility::getDceUidByContentElementRow(): Argument #1 ($row) must be of type array, null given

### ISSUE THREAD

**Issue by nhovratov** [a-r-m-i-n/dce#87]
**Versions**
- DCE version: **3.1.1**
- TYPO3 version: **12.4.6**
- PHP version: **8.1**

**Describe the bug**
This bug happens under certain conditions:
- There is no dce element with the uid 1 in the database (also not with deleted=1 flag)
- Insert a new DCE element at the **first** position in any column
- Save the new Content Element
- The error appears:

```
T3\Dce\Utility\DatabaseUtility::getDceUidByContentElementRow(): Argument #1 ($row) must be of type array, null given, called in /var/www/dce/Classes/Utility/DatabaseUtility.php on line 139
```

**Comment by a-r-m-i-n** [comment]
Do you use the FAL Viewhelper in your backend or Frontend templates? I had this case a fews days ago on Slack. https://typo3.slack.com/archives/C08CA1EP8/p1696073135046299

**Comment by nhovratov** [comment]
@a-r-m-i-n I think this is not related. It happens inside `TtContentLabel`.
![Screenshot 2023-10-09 at 11-57-34 TYPO3 Exception · EXT dce Dev Environment TYPO3 CMS 12 4 6](https://github.com/a-r-m-i-n/dce/assets/19343425/59791443-a6b4-4925-b328-053919fa8776)

**Comment by nhovratov** [comment]
This has something to do with DataHandler sending `edit[tt_content][1]` for inserting records at the first position. Normally this is a negative uid of the element before.

**Comment by nhovratov** [comment]
Have a look at the PR please, this fixes the issue in my project and local dve ddev setup.

**Comment by a-r-m-i-n** [comment]
Hmmmm.. I'm unable to reconstruct your issue and your Pull Request seems to postpone the issue to uid 2 only?

**Comment by nhovratov** [comment]
The key "1" is a special key. There is no "2". See: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Typo3CoreEngine/Database/Index.html#id1

**Comment by a-r-m-i-n** [comment]
Could you add a screenshot of that special key? I don't find it on the docs page you've linked.
Also, the special key "1" is unknown to me.

**Comment by nhovratov** [comment]
I also can't find it right now. You can have a look at the latest discussion on typo3-cms-coredev.
So, if you insert a new record at the first position you have a get request:
`edit[tt_content][1] = 'new'`
But, if you insert it **after** an existing element, it looks like this:
`edit[tt_content][-2] = 'new'`
So DataHandler knows where to put the new element.

**Comment by nhovratov** [comment]
I think you are right, 1 is not a special key. Let me recheck.

**Comment by a-r-m-i-n** [comment]
Okay. Just for the records: The issue was, the DataHandler uses the UID of the page, instead of the content element, when creating new content elements.

When a content element exists in database (even deleted=1 ones) no error occurres. But when the content element is missing entirely, null is being returned, which leads to the initial issue.

The fix of @nhovratov solves this issue.
