### ISSUE TITLE
After Upgrade 2.9.5 Exception

### ISSUE THREAD

**Issue by fischhase** [a-r-m-i-n/dce#89]
**Versions**
- DCE version: **2.9.5**
- TYPO3 version: **11.5.32**
- PHP version: **8.2**

**Describe the bug**
After updating the last TYPO3 11-Subversion to 11.5.32 (Securityupdate), Upgrade to DCE Version 2.9.5 and change from PHP 7.4 to 8.2 (needed because of TYPO3 Core) I now get an exception:
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Uninitialized string offset 0 in /usr/www/users/janjbs/typo3/typo3_src-11.5.32/typo3/sysext/extbase/Classes/Mvc/ExtbaseRequestParameters.php line 280

at TYPO3\CMS\Core\Error\ErrorHandler->handleError()
in /usr/www/users/janjbs/typo3/typo3_src-11.5.32/typo3/sysext/extbase/Classes/Mvc/ExtbaseRequestParameters.php line 280

at TYPO3\CMS\Extbase\Mvc\ExtbaseRequestParameters->setControllerActionName()
in /usr/www/users/janjbs/typo3/typo3_src-11.5.32/typo3/sysext/extbase/Classes/Mvc/Request.php line 345

at TYPO3\CMS\Extbase\Mvc\Request->setControllerActionName()
in /usr/www/users/janjbs/typo3/typo3_src-11.5.32/typo3/sysext/fluid/Classes/Core/Rendering/RenderingContext.php line 161

at TYPO3\CMS\Fluid\Core\Rendering\RenderingContext->setControllerAction()
in /usr/www/users/janjbs/typo3/typo3_src-11.5.32/typo3/sysext/fluid/Classes/View/AbstractTemplateView.php line 107

**First appearance of DCE:**
at TYPO3\CMS\Fluid\View\AbstractTemplateView->setTemplate()
in /usr/www/users/janjbs/webseite/janbintakies.de/typo3conf/ext/dce/Classes/Components/TemplateRenderer/StandaloneViewFactory.php line 118

at T3\Dce\Components\TemplateRenderer\StandaloneViewFactory->applyDceTemplateTypeToView()
in /usr/www/users/janjbs/webseite/janbintakies.de/typo3conf/ext/dce/Classes/Components/TemplateRenderer/StandaloneViewFactory.php line 83

**Comment by a-r-m-i-n** [comment]
Hi. With the stack trace only, it is hard for me to reconstruct the issue. Could you please provide more information about how the Frontend template (I assume the issue appears there) is set up?

Do you use inline template or file template? And could you please provide the template itself, and if it's a file, how the template path is defined?

Because it's "just" a warning, you could bypass the error by disabling warnings in exception handler - as a quick workaround.

**Comment by a-r-m-i-n** [comment]
@fischhase Please provide more information or I'm going to close the issue. Thanks.
