### ISSUE TITLE
Getting conflict with nnrestapi extension when disable DCE elements getting error in backend

### ISSUE THREAD

**Issue by MohsinQK** [a-r-m-i-n/dce#90]
https://github.com/a-r-m-i-n/dce/blob/8459b7fe71e92414ad1aa448f64b01765291c39e/Classes/Domain/Repository/DceRepository.php#L798C58-L798C58

TYPO3 V11, DCE V2.9.5
Here hidden restriction is not working.
if we disable one DCE Element in the backend then I get the following error in the backend.
if I uninstall the nnrestapi extension or change this to removeAll Restrictions then it works.
let me know if I can give you MR for this or if you will solve this in some other way.

<img width="1304" alt="image" src="https://github.com/a-r-m-i-n/dce/assets/1622975/fb3c4d4b-6100-4da5-90e3-90b1e7a5a013">

**Comment by a-r-m-i-n** [comment]
I've seen that this extension Xclasses the hidden restriction :/

https://bitbucket.org/99grad-team/nnrestapi/src/96bd5febbc00386791d5c16e7717a4f3fb6dbe60/ext_localconf.php#lines-48

**Comment by MohsinQK** [comment]
Hmm ok, looks like this needs to be fixed from nnrestapi extension. and not in DCE.
Thanks @a-r-m-i-n for your quick response.

**Comment by a-r-m-i-n** [comment]
You're welcome :)

**Comment by MohsinQK** [comment]
Created issue on nnresapi adding here link just for reference.
https://bitbucket.org/99grad-team/nnrestapi/issues/54/xclassed-hiddenrestriction-making-issue
