### ISSUE TITLE
Error 503 on saving DCE

### ISSUE THREAD

**Issue by rawsta** [a-r-m-i-n/dce#95]
**Versions**
- DCE version: **2.9.5**
- TYPO3 version: **11.5.33**
- PHP version: **8.2.7**

**Describe the bug**
After upgrading Typo3 to v11.5 (from v8.7) it's not possible to save an element.
At first, everything seem to work just fine. When I try to save, I get an error 503.
It looks like DCE(?) can't get the current UID which results in a wrong query.

It doesn't matter, if I try to edit an existing element or create a new one.

The only difference is that a new element can be saved once.
That new Element looses its columns and sets the columns to 99, which is invalid.
From that point on, I can only delete it.

```
Fri, 15 Dec 2023 10:06:57 +0100 [CRITICAL] request="8a8101bf2d3ff" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": 
Core: Exception handler (WEB: BE): Doctrine\DBAL\Exception\SyntaxErrorException, code #0, 
file /var/www/typo3_sources/typo3_src-11.5.33/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php, line 98: 
An exception occurred while executing 'SELECT * FROM `tt_content` WHERE (`uid` = ) AND (`tt_content`.`deleted` = 0)':

You have an error in your SQL syntax; check the manual 
that corresponds to your MariaDB server version for the right syntax to use near 
') AND (`tt_content`.`deleted` = 0)' at line 1 - 
{"mode":"WEB","application_mode":"BE","exception_class":"Doctrine\\DBAL\\Exception\\SyntaxErrorException","exception_code":0,
"file":"/var/www/typo3_sources/typo3_src-11.5.33/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","line":98,"message":
"An exception occurred while executing 'SELECT * FROM `tt_content` WHERE (`uid` = ) AND (`tt_content`.`deleted` = 0)':
\n\nYou have an error in your SQL syntax; 
check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND (`tt_content`.`deleted` = 0)' at line 1",
"request_url":"https://www.testdomain.de/typo3/record/edit?token=--AnonymizedToken--&edit%5Btt_content%5D%5B12501%5D=edit&returnUrl=%2Ftypo3%2Fmodule%2Fweb%2Flayout%3Ftoken%3D--AnonymizedToken--%26id%3D6606%23element-tt_content-12501&route=%2Frecord%2Fedit","exception":null}
```

I have not even a clue where to start to fix this.

**Comment by a-r-m-i-n** [comment]
Hi. This sounds very weird. That the colpos is set to 99 seems not to be a behavior of DCE itself. My guess is, that another extension is responsible for that. Could you try to disable all other extensions temporary, clear all caches and check if this behavior still occurs?

**Comment by rawsta** [comment]
The error came from one of our custom extensions. 
Sorry for the confusion. Since it only happened when saving DCEs, I thought it was the reason for the error. 
DCE was fine... our own extension wasn't.
