### ISSUE TITLE
Linking Files in CKE within an DCE doesn't create a REF to this file

### ISSUE THREAD

**Issue by tohett** [a-r-m-i-n/dce#97]
- DCE version: 3.1.2
- TYPO3 version: 12.4.9

Linking files – f.i. a pdf-file –  in a CK-editor within a DCE, doesn't create a reference to this pdf-file. So in the file list the column "REF" is still "-" and you can delete this file even tough it is in use.
This behaviour is the same in older versions.

**Comment by a-r-m-i-n** [comment]
Hi. Could you check if the following field config will fix your issue?

`<softref>typolink_tag,email[subst],url</softref>`

This is the same config used in bodytext field in tt_content table, just in XML style.

**Comment by tohett** [comment]
It does!!!! Thank you very much! Shouldn'T this snippet be part of the prepared configuration when creating a RTE-field? Anyway, thank you very much and have a merry christmas!

**Comment by a-r-m-i-n** [comment]
Yes, it should. I'm going to add the softref option to the RTE field preset.

Merry Christmas you too 🎅
