### ISSUE TITLE
Images in section (nested) do not work after update to typo3 version 12

### ISSUE THREAD

**Issue by marv2358** [a-r-m-i-n/dce#99]
**Versions**
- DCE version: 3.1.2
- TYPO3 version: 12.4.11
- PHP version: 8.2

**Describe the bug**
Images in section (nested) do not work after update to typo3 version 12
Furthermore, there is no update function for this in dce (<= 3.1.2). As soon as a new DCE element is created in which an image is used within the section element, the following error message appears.
<img width="1141" alt="dce-example" src="https://github.com/a-r-m-i-n/dce/assets/53895345/5edc1edd-ed14-4349-b358-65649e16f2b2">
<img width="830" alt="error" src="https://github.com/a-r-m-i-n/dce/assets/53895345/d8cb9ea7-9d02-49a0-a7f5-93b976e425bf">

In Typo3 v11, the following configuration works for the field in particular.

<img width="566" alt="Bildschirmfoto 2024-02-22 um 10 35 23" src="https://github.com/a-r-m-i-n/dce/assets/53895345/da954a97-4ccd-4642-bd0d-bf36403467ac">

However, a consideration of the mentioned configuration within the update function would be very helpful.

**Comment by a-r-m-i-n** [comment]
Please see https://github.com/a-r-m-i-n/dce/issues/73#issuecomment-1695750224

The error message you've posted is core related, so I'm unable to fix anything here. 

You should avoid using sections! Use the DCE container feature instead.
